(python3) PS D:\keras-segnet> & C:/Users/LIRINS/venv/python3/Scripts/python.exe d:/keras-segnet/Editable_SegNet.py
Using TensorFlow backend.
2018-11-23 14:54:39.440157: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-23 14:54:40.369573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 12.00GiB freeMemory: 9.92GiB
2018-11-23 14:54:40.381975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-23 14:54:41.765038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-23 14:54:41.772110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-11-23 14:54:41.775606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-11-23 14:54:41.779388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9589 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
Compiled: OK
train: OK==================>] 100%
        shapes: (100, 512, 512, 1), (100, 262144, 4)
        types:  uint8, float64
        memory: 25.0, 800.0 MB
d:/keras-segnet/Editable_SegNet.py:131: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  history = autoencoder.fit(train_data, train_label, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1)
Epoch 1/10
2018-11-23 14:56:00.254314: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.41GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
100/100 [==============================] - 21s 213ms/step - loss: 2.3711 - acc: 0.4591
Epoch 2/10
100/100 [==============================] - 12s 115ms/step - loss: 1.7042 - acc: 0.4954
Epoch 3/10
100/100 [==============================] - 12s 115ms/step - loss: 1.6200 - acc: 0.4430
Epoch 4/10
100/100 [==============================] - 12s 115ms/step - loss: 1.5889 - acc: 0.4176
Epoch 5/10
100/100 [==============================] - 12s 115ms/step - loss: 1.5694 - acc: 0.4045
Epoch 6/10
100/100 [==============================] - 11s 115ms/step - loss: 1.5545 - acc: 0.3932
Epoch 7/10
100/100 [==============================] - 11s 115ms/step - loss: 1.5426 - acc: 0.3920
Epoch 8/10
100/100 [==============================] - 11s 115ms/step - loss: 1.5319 - acc: 0.3844
Epoch 9/10
100/100 [==============================] - 12s 116ms/step - loss: 1.5224 - acc: 0.3755
Epoch 10/10
100/100 [==============================] - 12s 116ms/step - loss: 1.5145 - acc: 0.3774
test: OK==================>] 100%
        shapes: (20, 512, 512, 1), (20, 262144, 4)
        types:  uint8, float64
        memory: 5.0, 160.0 MB
Test score: 1.8311220407485962
Test accuracy: 0.5749775171279907
Traceback (most recent call last):
  File "d:/keras-segnet/Editable_SegNet.py", line 147, in <module>
    plot_results(output)
  File "d:/keras-segnet/Editable_SegNet.py", line 109, in plot_results
    rgb[:, :, 2] = gt
ValueError: could not broadcast input array from shape (512,512,3) into shape (512,512)
(python3) PS D:\keras-segnet>